---
deployment:
  tasks:
    - export NODE_ENV=production
    - npm install
    - npm run build
    - /bin/cp -r /home/istotbfw/.next /home/istotbfw/public_html/
    - /bin/cp -r /home/istotbfw/src/* /home/istotbfw/public_html/
    - /bin/cp -r /home/istotbfw/public/* /home/istotbfw/public_html/
    - npm start &