---
deployment:
  tasks:
    - export DEPLOYPATH=/home/istotbfw/public_html/
    - export REPOPATH=/home/istotbfw/repositories/istockuy-web
    - /bin/cp -R $REPOPATH/public/* $DEPLOYPATH/
    - /bin/cp -R $REPOPATH/src/* $DEPLOYPATH/
    - export NODE_ENV=production
    - npm install
    - npm run build
    - npm start &