---
deployment:
  tasks:
    - export NODE_ENV=production
    - npm install
    - npm run build
    - /bin/cp -r .next /home/istotbfw/public_html/
    - /bin/cp -r src/* /home/istotbfw/public_html/
    - /bin/cp -r public/* /home/istotbfw/public_html/
    - npm start &